// Fetches building footprint polygons from OpenStreetMap (Overpass API) and
// writes src/data/footprints.ts. Run once per new building: bun run fetch-footprints
import { writeFileSync } from 'node:fs'
import { buildings } from '../src/data/buildings'

type LngLat = [number, number]

// Primary mirror first; if it returns 4xx/5xx, fall through to the backups.
const OVERPASS_MIRRORS = [
  'https://overpass-api.de/api/interpreter',
  'https://overpass.kumi.systems/api/interpreter',
  'https://maps.mail.ru/osm/tools/overpass/api/interpreter',
]
const SEARCH_RADIUS_M = 60

type OverpassWay = {
  type: string
  id: number
  geometry?: { lat: number; lon: number }[]
}

function buildQuery(): string {
  const clauses = buildings
    .map(
      (b) =>
        `way(around:${SEARCH_RADIUS_M},${b.coordinates[1]},${b.coordinates[0]})["building"];`,
    )
    .join('\n')
  return `[out:json][timeout:60];(\n${clauses}\n);out geom;`
}

function pointInPolygon([lng, lat]: LngLat, polygon: LngLat[]): boolean {
  let inside = false
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const [xi, yi] = polygon[i]
    const [xj, yj] = polygon[j]
    const intersects =
      yi > lat !== yj > lat && lng < ((xj - xi) * (lat - yi)) / (yj - yi) + xi
    if (intersects) inside = !inside
  }
  return inside
}

function centroidOf(points: LngLat[]): LngLat {
  let lng = 0
  let lat = 0
  for (const [x, y] of points) {
    lng += x
    lat += y
  }
  return [lng / points.length, lat / points.length]
}

function distanceSq(a: LngLat, b: LngLat): number {
  const dx = a[0] - b[0]
  const dy = a[1] - b[1]
  return dx * dx + dy * dy
}

async function fetchOverpass(query: string): Promise<{ elements: OverpassWay[] }> {
  for (const mirror of OVERPASS_MIRRORS) {
    let res: Response
    try {
      res = await fetch(mirror, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: 'data=' + encodeURIComponent(query),
      })
    } catch (e) {
      console.warn(`Mirror ${mirror} threw: ${(e as Error).message} — trying next`)
      continue
    }
    if (!res.ok) {
      console.warn(`Mirror ${mirror} returned ${res.status} ${res.statusText} — trying next`)
      continue
    }
    return (await res.json()) as { elements: OverpassWay[] }
  }
  throw new Error('All Overpass mirrors failed')
}

async function main() {
  const json = await fetchOverpass(buildQuery())
  const polygons = json.elements
    .filter((e) => e.type === 'way' && (e.geometry?.length ?? 0) >= 4)
    .map((w) => w.geometry!.map((g): LngLat => [g.lon, g.lat]))

  const footprints: Record<string, LngLat[]> = {}
  const missing: string[] = []

  for (const building of buildings) {
    const containing = polygons.filter((p) => pointInPolygon(building.coordinates, p))
    const candidates = containing.length > 0 ? containing : polygons
    if (candidates.length === 0) {
      missing.push(building.id)
      continue
    }
    const best = candidates.reduce((a, b) =>
      distanceSq(centroidOf(a), building.coordinates) <=
      distanceSq(centroidOf(b), building.coordinates)
        ? a
        : b,
    )
    footprints[building.id] = best
  }

  const lines = [
    '// GENERATED by scripts/fetch-footprints.ts — do not edit by hand.',
    '// Regenerate with: bun run fetch-footprints',
    'export const footprints: Record<string, [number, number][]> = {',
    ...Object.entries(footprints).map(
      ([id, points]) =>
        `  '${id}': [${points.map(([lng, lat]) => `[${lng}, ${lat}]`).join(', ')}],`,
    ),
    '}',
    '',
  ]
  writeFileSync('src/data/footprints.ts', lines.join('\n'))

  console.log(`Wrote footprints for ${Object.keys(footprints).length}/${buildings.length} buildings.`)
  if (missing.length > 0) {
    console.log(`No footprint found (fallback rectangle will render): ${missing.join(', ')}`)
  }
}

await main()
